[project]
name = "test-scip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "tree-sitter>=0.25.1",
    "tree-sitter-language-pack>=0.9.0",
]
